### ISSUE TITLE
Quotes aren't changed

### ISSUE THREAD

**Issue by matteosuppo** [vvakame/typescript-formatter#59]
Even if my tslint.json contains

```
        "quotemark": [
            true,
            "double"
        ],
```

tsfmt doesn't change a single quote to a double quote

**Comment by vvakame** [comment]
sounds good.
but tsfmt is wrapper of [TypeScript Language Service](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#pretty-printer-using-the-ls-formatter).
I don't do that. sorry.

**Comment by darcyparker** [comment]
@matteosuppo and @vvakame - are you aware of a request to add the option to set the preferred quotemark (single or double) in `ts.FormatCodeOptions`?  I couldn't find one here: https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue%20FormatCodeOptions and wanted to check with you before creating such a feature request.

**Comment by matteosuppo** [comment]
I'm not aware of anything like that.

**Comment by joehannes-zz** [comment]
ping ... maybe I'm basically missing something else. but is this still valid. because I got the issue in my neovim-setup that when I neoformat with tsfmt I don't get the double quotes replaced by single quotes.
though the linter is showing errors, so nvim is picking the linting up.
don't know, maybe it's something else ... just, ping ...
